version: '3'

services:
  nginx:
    build: ./nginx
    container_name: nginx-proxy
    depends_on:
      - springboot
    ports:
      - "9000:80"

  postgres:
    image: postgres:16-alpine
    container_name: db
    environment:
        POSTGRES_DB: todo
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=viet.nguyen@th-koeln.de
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=8080
    ports:
      - "9001:8080"

  springboot:
    build:
      dockerfile: Dockerfile_prod
    container_name: springboot-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres

volumes:
  postgres-data: